package presentation;

import javax.swing.JOptionPane;
import java.util.Calendar;
import java.util.GregorianCalendar;

public class AdmissionForm extends javax.swing.JFrame
{

    /** Creates new form AdmissionForm */
    public AdmissionForm()
    {
        initComponents();
        
        GregorianCalendar gc = new GregorianCalendar();
        int startYear = gc.get(Calendar.YEAR);
        int endYear = startYear + 8;
        for (int i = startYear; i < endYear; i++)
            cbYear.addItem(Integer.toString(i));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        admissionGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        rbDegreeProgram = new javax.swing.JRadioButton();
        rbNonDegreeProgram = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listPrograms = new javax.swing.JList();
        jLabel2 = new javax.swing.JLabel();
        txtEmailAddress = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cbMonth = new javax.swing.JComboBox();
        cbYear = new javax.swing.JComboBox();
        cbVerified = new javax.swing.JCheckBox();
        btnApply = new javax.swing.JButton();
        javax.swing.JButton btnExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Admission Form");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Admission Type"));

        admissionGroup.add(rbDegreeProgram);
        rbDegreeProgram.setSelected(true);
        rbDegreeProgram.setText("Degree Program");
        rbDegreeProgram.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actionTypeRadioButtonActionPerformed(evt);
            }
        });

        admissionGroup.add(rbNonDegreeProgram);
        rbNonDegreeProgram.setText("Non-Degree Program");
        rbNonDegreeProgram.setToolTipText("");
        rbNonDegreeProgram.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actionTypeRadioButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbDegreeProgram)
                .addGap(18, 18, 18)
                .addComponent(rbNonDegreeProgram)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbDegreeProgram)
                    .addComponent(rbNonDegreeProgram))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setText("Program:");

        listPrograms.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "MSCS\t", "MSEE", "MBA" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listPrograms);

        jLabel2.setText("Email Address:");

        jLabel3.setText("Graduation date:");
        jLabel3.setToolTipText("");

        cbMonth.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));

        cbVerified.setText("Verified");

        btnApply.setText("Apply");
        btnApply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApplyActionPerformed(evt);
            }
        });

        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addComponent(txtEmailAddress)
                            .addComponent(cbVerified)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(cbMonth, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbYear, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnApply)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnExit)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEmailAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(cbMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbVerified)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExit)
                    .addComponent(btnApply))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.getAccessibleContext().setAccessibleName("Admission");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void actionTypeRadioButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_actionTypeRadioButtonActionPerformed
    {//GEN-HEADEREND:event_actionTypeRadioButtonActionPerformed
        if (rbDegreeProgram.isSelected())
            enableCreditCardControls(true);
        else if (rbNonDegreeProgram.isSelected())
            enableCreditCardControls(false);
    }//GEN-LAST:event_actionTypeRadioButtonActionPerformed

    private void enableCreditCardControls(boolean enable)
    {
        listPrograms.setEnabled(enable);
        txtEmailAddress.setEnabled(enable);
        cbMonth.setEnabled(enable);
        cbYear.setEnabled(enable);
        cbVerified.setEnabled(enable);
    }
    
    private void btnApplyActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnApplyActionPerformed
    {//GEN-HEADEREND:event_btnApplyActionPerformed
        String msg = "";
        if (rbDegreeProgram.isSelected())
        {
            msg = "Apply " + (String)listPrograms.getSelectedValue() +
                  "\nEmail address + " + txtEmailAddress.getText() +
                  "\nGraduation date: " +
                  (String)cbMonth.getSelectedItem() +
                   ", " + (String)cbYear.getSelectedItem();
            if (cbVerified.isSelected())
                msg+= "\nGraduation date\n has been verified.";
            else
                msg+= "\nGraduation date has not been verified.";
        }
        else
        {
            msg = "Applicants will not be verified.";
        }
        JOptionPane.showMessageDialog(this, msg);
        listPrograms.setSelectedIndex(0);
        txtEmailAddress.setText("");
        cbMonth.setSelectedIndex(0);
        cbYear.setSelectedIndex(0);
        cbVerified.setSelected(false);        

    }//GEN-LAST:event_btnApplyActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnExitActionPerformed
    {//GEN-HEADEREND:event_btnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        java.awt.EventQueue.invokeLater(new Runnable()
        {

            public void run()
            {
                AdmissionForm frame = new AdmissionForm();
                frame.setVisible(true);
                frame.setLocationRelativeTo(null);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup admissionGroup;
    private javax.swing.JButton btnApply;
    private javax.swing.JComboBox cbMonth;
    private javax.swing.JCheckBox cbVerified;
    private javax.swing.JComboBox cbYear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList listPrograms;
    private javax.swing.JRadioButton rbDegreeProgram;
    private javax.swing.JRadioButton rbNonDegreeProgram;
    private javax.swing.JTextField txtEmailAddress;
    // End of variables declaration//GEN-END:variables
}
