package presentation;

import javax.swing.JTextField;
import java.util.ArrayList;

import business.Computer;
import dataaccess.*;

public class ComputerManagementForm extends javax.swing.JFrame {
    
    // declare global variables for the form
    ComputerDataFile computerData;
    ArrayList<Computer> computers;
    Computer newComputer = null;
    boolean filling = false;
    
    /** Creates new form ComputerMaintenanceFrame */
    public ComputerManagementForm() {
        initComponents();
        
        // fill the computers combo box
        computerData = new ComputerDataFile();
        computers = computerData.getComputers();
        fillComboBox(computers);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtPartnumber = new javax.swing.JTextField();
        cbComputer = new javax.swing.JComboBox();
        txtDescription = new javax.swing.JTextField();
        txtPrice = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnAccept = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Computer Management System");

        jLabel1.setText("Select Computer");

        jLabel2.setText("Part Number:");

        jLabel3.setText("Description:");

        jLabel4.setText("Unit Price:");

        txtPartnumber.setEditable(false);
        txtPartnumber.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textBoxFocusGained(evt);
            }
        });

        cbComputer.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbComputer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbComputerActionPerformed(evt);
            }
        });

        txtDescription.setEditable(false);
        txtDescription.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textBoxFocusGained(evt);
            }
        });

        txtPrice.setEditable(false);
        txtPrice.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textBoxFocusGained(evt);
            }
        });

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnAccept.setText("Accept");
        btnAccept.setEnabled(false);
        btnAccept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcceptActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.setEnabled(false);
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnExit.setMnemonic('x');
        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPartnumber, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDescription)
                            .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnAdd)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEdit)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnDelete)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAccept)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCancel))
                            .addComponent(cbComputer, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(btnExit, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbComputer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtPartnumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel)
                    .addComponent(btnAccept)
                    .addComponent(btnDelete)
                    .addComponent(btnEdit)
                    .addComponent(btnAdd))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExit)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fillComboBox(ArrayList<Computer> a) {
        filling = true;
        cbComputer.removeAllItems();
        for (Computer c : a)
            cbComputer.addItem(c);
        filling = false;
    }    

    private void selectComputer(Computer c) {
        cbComputer.setSelectedItem(c);
    }
    
    private Computer getCurrentComputer() {
        return (Computer) cbComputer.getSelectedItem();
    }
    
    private void showComputer(Computer c) {
        txtPartnumber.setText(c.getPartnumber());
        txtDescription.setText(c.getDescription());
        txtPrice.setText(c.getFormattedPrice());
    }
    
    private void clearFields() {
        txtPartnumber.setText("");
        txtDescription.setText("");
        txtPrice.setText("");
    }
    
    // return a new Computer object with the data in the text fields
    private Computer getComputer() {
        Computer c = new Computer();
        c.setPartnumber(txtPartnumber.getText());
        c.setDescription(txtDescription.getText());
        c.setFormattedPrice(txtPrice.getText());
        return c;
    }
    
    private void setAddMode() {
        txtPartnumber.setEditable(true);
        txtPartnumber.setFocusable(true);
        txtPartnumber.requestFocusInWindow();
        txtDescription.setEditable(true);
        txtDescription.setFocusable(true);
        txtPrice.setEditable(true);
        txtPrice.setFocusable(true);
    }
    
    private void setEditMode() {
        txtDescription.setEditable(true);
        txtDescription.setFocusable(true);
        txtDescription.requestFocusInWindow();
        txtPrice.setEditable(true);
        txtPrice.setFocusable(true);
    }
    
    private void setDisplayMode() {
        txtPartnumber.setEditable(false);
        txtPartnumber.setFocusable(false);
        txtDescription.setEditable(false);
        txtDescription.setFocusable(false);
        txtPrice.setEditable(false);
        txtPrice.setFocusable(false);
    }
    
    private void setAddEditMode(boolean e) {
        btnAdd.setEnabled(!e);
        btnEdit.setEnabled(!e);
        btnDelete.setEnabled(!e);
        btnAccept.setEnabled(e);
        btnCancel.setEnabled(e);
    }
    
    private boolean isValidData() {
        DataValidator dv = new DataValidator();
        if (newComputer != null)
            return 
                dv.isPresent(this.txtPartnumber, "Computer Code") && 
                dv.isPresent(this.txtDescription, "Description") && 
                dv.isPresent(this.txtPrice, "Unit Price") && 
                dv.isDouble(this.txtPrice, "Unit Price");
        else
            return 
                dv.isPresent(this.txtDescription, "Description") && 
                dv.isPresent(this.txtPrice, "Unit Price") &&
                dv.isDouble(this.txtPrice, "Unit Price");
    }    
    
    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        if (newComputer != null) {
            newComputer = null;
        }
        this.setDisplayMode();
        this.showComputer(this.getCurrentComputer());
        this.setAddEditMode(false);
        this.cbComputer.requestFocusInWindow();
    }//GEN-LAST:event_btnCancelActionPerformed
    
    private void btnAcceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcceptActionPerformed
        if (isValidData()) {
            if (newComputer != null) {
                newComputer = this.getComputer();
                computerData.addComputer(newComputer);
                computers.add(newComputer);
                this.fillComboBox(computers);
                this.selectComputer(newComputer);
                newComputer = null;
            } else {
                Computer cc = this.getCurrentComputer();
                Computer c = this.getComputer();
                cc.setDescription(c.getDescription());
                cc.setPrice(c.getPrice());
                computerData.updateComputer(cc);
                this.fillComboBox(computers);
                this.selectComputer(cc);
                this.showComputer(this.getCurrentComputer());
            }
            this.setDisplayMode();
            this.setAddEditMode(false);
            this.cbComputer.requestFocusInWindow();
        }
    }//GEN-LAST:event_btnAcceptActionPerformed
    
    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        Computer c = this.getComputer();
        computerData.deleteComputer(c);
        computers.remove(c);
        this.fillComboBox(computers);
        this.selectComputer(computers.get(0));
        this.showComputer(computers.get(0));
        this.cbComputer.requestFocusInWindow();
    }//GEN-LAST:event_btnDeleteActionPerformed
    
    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        this.setAddEditMode(true);
        this.setEditMode();
    }//GEN-LAST:event_btnEditActionPerformed
    
    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        newComputer = new Computer();
        this.clearFields();
        this.setAddEditMode(true);
        this.setAddMode();
    }//GEN-LAST:event_btnAddActionPerformed
    
    private void textBoxFocusGained(java.awt.event.FocusEvent evt)//GEN-FIRST:event_textBoxFocusGained
    {//GEN-HEADEREND:event_textBoxFocusGained
        if (evt.getComponent() instanceof JTextField) {
            JTextField t = (JTextField) evt.getComponent();
            t.selectAll();
        }
    }//GEN-LAST:event_textBoxFocusGained
    
    private void cbComputerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbComputerActionPerformed
        if (!filling) {
            Computer p = (Computer) cbComputer.getSelectedItem();
            this.showComputer(p);
        }
    }//GEN-LAST:event_cbComputerActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
                System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                ComputerManagementForm frame = new ComputerManagementForm();
                frame.setVisible(true);
                frame.setLocationRelativeTo(null);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAccept;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnExit;
    private javax.swing.JComboBox cbComputer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtDescription;
    private javax.swing.JTextField txtPartnumber;
    private javax.swing.JTextField txtPrice;
    // End of variables declaration//GEN-END:variables
    
}